DisplayRazor/Models/ChipCardModel.cs
using Domain;
using System;
using System.ComponentModel.DataAnnotations;

namespace DisplayRazor.Models {
    /// <summary>
    /// This is an ACL implementation in order to be robust against future changes.
    /// </summary>
    public class ChipCardModel : IChipCard {
        [Display(Name = "Valid from")]
        public DateTime ValidFrom { get; set; }

        [Display(Name = "Valid to")]
        public DateTime ValidTo { get; set; }

        [Display(Name = "Is Active")]
        public bool Active { get; set; }

        [Display(Name = "Chipcard UId")]
        public string ChipUId { get; set; }

        public ChipCardModel(DateTime validFrom, DateTime validTo, bool active, string chipUId) {
            ValidFrom = validFrom;
            ValidTo = validTo;
            Active = active;
            ChipUId = chipUId ?? throw new ArgumentNullException(nameof(chipUId));
        }

        public ChipCardModel() { }

        public ChipCardModel(IChipCard toConvert) :
            this(toConvert.ValidFrom, toConvert.ValidTo, toConvert.Active, toConvert.ChipUId) { }
    }
}

DisplayRazor/Models/ErrorViewModel.cs
using System;

namespace DisplayRazor.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DisplayRazor/Models/ResetModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DisplayRazor.Models {
    public class ResetModel {

        [Required]
        [Display(Name ="Maxium tries")]
        public int Tries { get; set; }
    }
}

DisplayRazor/Controllers/ChipCardController.cs
using Config;
using Core.Interfaces;
using DisplayRazor.Models;
using Domain;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DisplayRazor.Controllers {
    public class ChipCardController : Controller, IChipCardWhereGetter, IChipCardResetter {
        private int tries = -1;

        /// <summary>
        /// Allows to get and set the private variable tries.
        /// At the same time no varialbe is exposed only interfaces.
        /// This is atleast needed for testing.
        /// </summary>
        public int Tries { get => tries; set => tries = value; }

        [HttpPost]
        public IActionResult Display(string Active, string ValidFrom, string ValidTo, string IdLike) {
            ViewData["Message"] = "";

            bool? active = Active.ToNullable<bool>();
            var vFrom = ValidFrom.ToNullableDateTime();
            var vTo = ValidTo.ToNullableDateTime();
            string id = IdLike?.Trim() ?? "";

            ViewData["Active"] = Active;
            ViewData["ValidFrom"] = ValidFrom;
            ViewData["ValidTo"] = ValidTo;
            ViewData["IdLike"] = id;

            return DisplayWhere(card => {
                bool choose = true;
                choose &= active.HasValue ? card.Active == active.Value : true;
                choose &= vFrom.HasValue ? card.ValidFrom >= vFrom.Value : true;
                choose &= vTo.HasValue ? card.ValidTo <= vTo.Value : true;
                choose &= card.ChipUId.Contains(id);
                return choose;
            });
        }

        /// <summary>
        /// This function either return the display page or the reset page if something went wrong.
        /// It also allows to filter the passed chipcards to the display page.
        /// </summary>
        /// <param name="where">This function specifies what conditions have to be met for the chipcards in order to be
        /// bassed to the display page.</param>
        private IActionResult DisplayWhere(Func<IChipCard, bool> where) {
            try {
                var task = Where(where);
                task.Wait();
                return View("Display", task.Result.Select(card => new ChipCardModel(card)));
            }
            catch (Exception) {
                ViewData["Message"] = "An error occured at the retrivial ob the stored chipcards! It might not be initalised. Please initalise it through resetting.";
                var reset = new ResetModel();
                return View("ResetApp", reset);
            }
        }

        [HttpGet]
        public IActionResult Display() {
            ViewData["Message"] = "";
            return DisplayWhere(card => true);//gets alls
        }

        [HttpGet]
        public IActionResult ResetApp() {
            var reset = new ResetModel();
            return View(reset);
        }

        [HttpPost]
        public IActionResult ResetApp(ResetModel reset) {
            if (!ModelState.IsValid) {
                ViewData["Message"] = "Please enter a number for the tries.";
                return View(reset);
            }
            tries = reset.Tries;
            try {
                var task = Reset();
                task.Wait();
                if (!task.Result) {
                    ViewData["Message"] = $"Reset failed after {reset.Tries} attempts!";
                    return View(reset);
                }
                ViewData["Message"] = "Sucessfully resetted the cached chip cards.";

            }
            catch (Exception ex) {
                ViewData["Message"] = "An error occured: " + ex.ToString();
            }
            return View(reset);

        }


        public IActionResult Documentation() {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<HashSet<IChipCard>> LikeId(string ChipUId) {
            var storageGetter = ChipCardWhereGetterFactory.WhereFromStorage();
            return await storageGetter.LikeId(ChipUId);
        }

        public async Task<HashSet<IChipCard>> Within(DateTime fromIncluding, DateTime tillIncluding) {
            var storageGetter = ChipCardWhereGetterFactory.WhereFromStorage();
            return await storageGetter.Within(fromIncluding, tillIncluding);
        }

        public async Task<HashSet<IChipCard>> ByActive(bool isActive) {
            var storageGetter = ChipCardWhereGetterFactory.WhereFromStorage();
            return await storageGetter.ByActive(isActive);
        }

        public async Task<HashSet<IChipCard>> Where(Func<IChipCard, bool> where) {
            var storageGetter = ChipCardWhereGetterFactory.WhereFromStorage();
            return await storageGetter.Where(where);
        }

        public async Task<HashSet<IChipCard>> All() {
            var storageGetter = ChipCardWhereGetterFactory.WhereFromStorage();
            return await storageGetter.All();
        }


        public async Task<bool> Reset() {
            var resetter = ChipCardResetterFactory.NetWorkStorageResetter(tries);
            return await resetter.Reset();
        }
    }
}

DisplayRazor/Views/ChipCard/Display.cshtml
@model IEnumerable<DisplayRazor.Models.ChipCardModel>
@{
    ViewData["Title"] = "Display";
}
<h2>@ViewData["Title"]</h2>

@if (!string.IsNullOrWhiteSpace(ViewData["Message"] as string)) {
    < h3 > @ViewData["Message"] </ h3 >
}


@using (Html.BeginForm(FormMethod.Post)) {
    <table class="table-condensed">
        <tr>
            <td class="text-center">
                Active:
            </td>
            <td class="text-center">
                Valid from (including):
            </td>
            <td class="text-center">
                Valid to (including):
            </td>
            <td class="text-center">
                @Html.LabelFor(m => m.First().ChipUId) like:
            </td>
        </tr>
        <tr>
            <td class="text-center">
                @{
                    try {
                        @Html.CheckBox("Active", (bool)ViewData["ValidTo"])
                    }
                    catch {
                        @Html.CheckBox("Active")
                    }
                }

            </td>
            <td class="text-center">
                @Html.TextBox("ValidFrom", String.Format("{0:d}",ViewData["ValidFrom"] as string ?? ""),
               new { @class = "datefield", type = "date"  })
            </td>
            <td class="text-center">
                @Html.TextBox("ValidTo", String.Format("{0:d}", ViewData["ValidTo"] as string ?? ""),
                new { @class = "datefield", type = "date"  })
            </td>
            <td class="text-center">
                @Html.TextBox("IdLike",ViewData["IdLike"])
            </td>
        </tr>

    </table>
    <div>
        <input type="submit" value="Filter" />
    </div>
}
<script type="text/javascript">
    var checkbox = document.getElementById("Active");
    checkbox.indeterminate = true;
</script>
<p>
    @using (Html.BeginForm("Display", "ChipCard", FormMethod.Get)) {
        <div>
            <input type="submit" value="Get All" />
        </div>
    }
</p>

@if (Model.Any()) {
    <table class="table">
        <thead>
            <tr>
                <td>@Html.LabelFor(m => m.First().ChipUId)</td>
                <td>@Html.LabelFor(m => m.First().ValidFrom)</td>
                <td>@Html.LabelFor(m => m.First().ValidTo)</td>
                <td>@Html.LabelFor(m => m.First().Active)</td>
            </tr>
        </thead>
        @foreach (var card in Model) {
            <tr>
                <td>@card.ChipUId</td>
                <td>@card.ValidFrom</td>
                <td>@card.ValidTo</td>
                <td>@card.Active</td>
            </tr>
        }
    </table>
}
else {
    <h3>No chipcards to display!</h3>
}

DisplayRazor/Views/ChipCard/Documentation.cshtml
@{
    ViewData["Title"] = "Dokumentation";
}
<h2>@ViewData["Title"]</h2>

<div>
    <h2>Architectural Overview</h2>
    <img src="~/images/Overview.png" width="30%">
    <p>
        The general architecture follows an onion design as it is common within domain driven desgin (DDD). In Addition to the onion layout a plugin infastructure is followed, where the outer service layers "plugin into" the inner ones and are replacable, as they only fullfill their infastructual demands. In addition the SOLID principles are followed for the implementation and can even be seen in the UML Diagramm.
    </p>
    <p>
        The domain which only contains of the ChipCard entity is in the middle. Depending from the customer needs in the future this domain might grow. The Config and Core are basicly Service layers but due to dependencies they are seperated in two projects. At the outside the DisplayRazor as an MVC project can be found. This project allows the user to controll the application in a server-client-manner. The retrivers itention is to get the information from the Source and then it is stored through the Storage on the local harddrive.
    </p>
    <p>The storage project exists in order to persist the data from the retriver. This decision was made in order to circumwent the not responding and slow part, with the downside of a server side copy of the retriver and the need to resett if new data is needed.</p>
    <p>An advantage of this architecture is the ease of change and the high grade of decoubleing of its compontents. Due to this decoupling the swapping of infastrucutre components or even adding new ones is quite simple.</p>
    <p>The downside is that implementing of a new domain entity is more time demanding as in a simpler approach. A simpler aproach could have been to just have a MVC and put everything including the Retriver in the Controller. Unfortunatly the complexity of a programm is a invariant and is only depending on the functional or non functional demands. Therefore you can either have a fast start with a slowdown with each added component or a slow start with a steady speed as future changes are easaly handable.</p>
</div>

<div>
    <h2>Architectural Details</h2>
    <img src="~/images/Full.png" width="80%"/>

</div>
<div>
    <h2>Areas of improvement depending on customer and future project needs</h2>
    <ul>
        <li>At the moment the storage is just a simple dump to the file System. This might be replaced through an database if the need to sync and manage multible sources at the same time arises</li>
        <li>An authentification might be added to allow only allowed users to access the data and to trigger a delite. In this case Credientials and Credential Services will be needed in the Domain and Core in addition to a Right Managment System.</li>
        <li>At the moment the web interface is realised "old school" like through a MVC and razors if the client requests a modern feeling single page application (SPA) the DisplayRazor can be replaced through an DisplaySPA, which achives this through angular or react. In the beginning the DisplayRazor can be used side by side to the new SPA in order to smoth out transitions.</li>
        <li>The storage implementation deletes the whole storage at the moment. This might not be desirable as old chipcards which are not provided anymore are lost. This can be changed. In this case it would be wise to implement a IChipCardUpdater alongside the existing IChipCardResetter</li>
        <li>If a microarchitecture is desired the whole infastruce points can be sepreated through a REST Inface.</li>
        <li>A dedicated Rest Inface can be easliy added.</li>
        <li>The resett process can be written asyncrhonus to refresh the local copy in periodic intervalls. In that case it would be wise to store it in a Temp_Intermediate.bin and only if the process finished to replace the exisitng one. Alternativly the improvement regarding a insert using update and create would also be feasiable.</li>
        <li>For better usablity the Settings file might be made adible by a user. This should be realised through adding a SettingsController in the MVC.</li>
        <li>CodedUI tests for testing the GUI should be added in order to streamline and get rid of the manual testing. This would also improve consistency and would at leas indirectly define expected design and behaviour.</li>
    </ul>
    <h2>Areas of architectual implementation improvement</h2>
    <p>Unfortuniatly time is a limited resource and therefore there are allways some shortcomings.</p>
    <ul>
        <li>A better implementation would be if Config starts DisplayRazor and not the other way around. In this case DisplayRazor would be implemented as a DLL and to a degree it would even be replacable douring runtime as it is the case for the other infastructure services. With further work it can even be written to be fully replacable douring runtime. If such a behaviour would be wanted it would be wise to think about at at least thrice, because erros and behaviour quirks which would be testable and which would show up at compile time are now runtime erros and therefore they can easily impact the user experience.</li>
        <li>The ChipCardController is not a strict implementation of SOLID. It does only one thing in regard to the ChipCard. In this point it can be considered to fullfill the single responsibilty, but it implements two comply diffrent interfaces displaying that it actually does two completly diffrent things. Therefore it should be seperated in a ChipCardGetterController and a ChipCardResetterController.</li>
    </ul>

</div>

DisplayRazor/Views/ChipCard/ResetApp.cshtml
@model DisplayRazor.Models.ResetModel
@{
    ViewData["Title"] = "Rest";
}
<h2>@ViewData["Title"]</h2>
@if (!string.IsNullOrEmpty(ViewData["Message"] as string)){
    <h3>@ViewData["Message"]</h3>
}


<p>The reset button allows to delete the cached chipcards and retrieves them from the service provider.</p>
<p>This Option should be used if the server is initalised or if new data is needed. The operation may take some time or and it might fail, if the maximum number of tries is exceedet.</p>
<p>The operation cann't be rolled back!</p>
<p>If a negative number is entered the default settiengs for the tries are used.</p>

@using(Html.BeginForm("ResetApp", "ChipCard",FormMethod.Post)){
    <div>
        @Html.LabelFor(m => m.Tries)<br />
        @Html.TextBoxFor(m=>m.Tries)<br />
        @Html.ValidationMessageFor(m=>m.Tries)
    </div>
    <div>
        <input type="submit"  value="Reset"/>
    </div>
}

DisplayRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nexus Developer Exercise</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="ChipCard" asp-action="Display" class="navbar-brand">Nexus Developer Exercise</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="ChipCard" asp-action="Display">Display ChipCards</a></li>
                    <li><a asp-area="" asp-controller="ChipCard" asp-action="ResetApp">Reset stored ChipCards</a></li>
                    <li><a asp-area="" asp-controller="ChipCard" asp-action="Documentation">Documentation</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Nexus Developer Exercise</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>